const menu = [
    {
      id: 1,
      title: 'Rasberry pancakes',
      category: 'breakfast',
      price: 7.95,
      img: './images/item-1.jpeg',
      desc: `One of the best pancakes you could ever taste with a special Rasberry flavour `,
    },
    {
      id: 2,
      title: 'Pizza Lizza',
      category: 'lunch',
      price: 11.95,
      img: './images/item-2.jpeg',
      desc: `A flattened disk of bread dough topped with some combination of olive oil, oregano, tomato, olives, mozzarella `,
    },
    {
      id: 3,
      title: 'Vegetable Juice',
      category: 'Drinks',
      price: 6.95,
      img: './images/item-3.jpeg',
      desc: `Vegetable juice is a blended vegetables boost your immune system, remove toxins from your body, aid digestion and help you lose weight.`,
    },
    {
      id: 4,
      title: 'Elegant Kickoff  ',
      category: 'breakfast',
      price: 13.95,
      img: './images/item-4.jpeg',
      desc: `For the most nutritious breakfast, we offer the healthiest breakfast: fruits, vegetables, grains, protein. `,
    },
    {
      id: 5,
      title: 'They SeeMe Rolln',
      category: 'lunch',
      price: 12.95,
      img: './images/item-5.jpeg',
      desc: `A Chinese dish roll of thin pastry filled with vegetables and meat, beyond delicious . `,
    },
    {
      id: 6,
      title: 'Fruity Lotty',
      category: 'Drinks',
      price: 6.95,
      img: './images/item-6.jpeg',
      desc: `Our Fruit juice is 100% pure juice made from the fresh whole fruit, No added sugars, NO sweeteners, NO preservatives, No flavourings or colourings`,
    },
    {
      id: 7,
      title: 'lasagna ya ',
      category: 'breakfast',
      price: 8.95,
      img: './images/item-7.jpeg',
      desc: `A rich and creamy whole-wheat pasta dish filled layer by layer with refreshingly fresh onions and garlic, lathered in a succulent sauce and topped with imported, premium quality mozzarella. `,
    },
    {
      id: 8,
      title: 'Energizer',
      category: 'lunch',
      price: 12.95,
      img: './images/item-8.jpeg',
      desc: `Retain energy. carbohydrates, fat, protein, vitamins, and minerals are the key nutrients that make up a healthy, balanced diet. `,
    },
    {
      id: 9,
      title: 'Green N Yellow',
      category: 'Drinks',
      price: 7.95,
      img: './images/item-9.jpeg',
      desc: `Lemon tea is a low-sugar, low-calorie way to add a range of vitamins and minerals to your diet.`,
    },
  ];
  export default menu;
  